apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: chaos-mesh
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: chaos-mesh
  namespaceSelector:
    matchNames:
      - chaos-mesh
  endpoints:
    - port: metrics
      interval: 15s

